services:
  api:
    build: .
    container_name: bemagro_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    environment:
      - DATABASE_URL
      - REDIS_URL
      - SECRET_KEY
      - ENV
      - MAPBOX_TOKEN
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: .
    container_name: bemagro_worker
    command: celery -A app.worker worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  flower:
    build: .
    container_name: bemagro_flower
    command: celery -A app.worker flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: bemagro_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgis/postgis:15-3.3
    container_name: bemagro_postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
